/** 经卷 id → 英文卷名/简称（KJV 目录与顶栏；离线 API 不可用时兜底）。 */
import { isEnglishBibleVersion } from './bible_version';
import type { BibleBook } from './api_core';

export const BOOK_EN_NAME: Record<string, string> = {
  GEN: 'Genesis',
  EXO: 'Exodus',
  LEV: 'Leviticus',
  NUM: 'Numbers',
  DEU: 'Deuteronomy',
  JOS: 'Joshua',
  JDG: 'Judges',
  RUT: 'Ruth',
  '1SA': '1 Samuel',
  '2SA': '2 Samuel',
  '1KI': '1 Kings',
  '2KI': '2 Kings',
  '1CH': '1 Chronicles',
  '2CH': '2 Chronicles',
  EZR: 'Ezra',
  NEH: 'Nehemiah',
  EST: 'Esther',
  JOB: 'Job',
  PSA: 'Psalms',
  PRO: 'Proverbs',
  ECC: 'Ecclesiastes',
  SNG: 'Song of Solomon',
  ISA: 'Isaiah',
  JER: 'Jeremiah',
  LAM: 'Lamentations',
  EZK: 'Ezekiel',
  DAN: 'Daniel',
  HOS: 'Hosea',
  JOL: 'Joel',
  AMO: 'Amos',
  OBA: 'Obadiah',
  JON: 'Jonah',
  MIC: 'Micah',
  NAM: 'Nahum',
  HAB: 'Habakkuk',
  ZEP: 'Zephaniah',
  HAG: 'Haggai',
  ZEC: 'Zechariah',
  MAL: 'Malachi',
  MAT: 'Matthew',
  MRK: 'Mark',
  LUK: 'Luke',
  JHN: 'John',
  ACT: 'Acts',
  ROM: 'Romans',
  '1CO': '1 Corinthians',
  '2CO': '2 Corinthians',
  GAL: 'Galatians',
  EPH: 'Ephesians',
  PHP: 'Philippians',
  COL: 'Colossians',
  '1TH': '1 Thessalonians',
  '2TH': '2 Thessalonians',
  '1TI': '1 Timothy',
  '2TI': '2 Timothy',
  TIT: 'Titus',
  PHM: 'Philemon',
  HEB: 'Hebrews',
  JAS: 'James',
  '1PE': '1 Peter',
  '2PE': '2 Peter',
  '1JN': '1 John',
  '2JN': '2 John',
  '3JN': '3 John',
  JUD: 'Jude',
  REV: 'Revelation',
};

export const BOOK_EN_ABBR: Record<string, string> = {
  GEN: 'Gen',
  EXO: 'Ex',
  LEV: 'Lev',
  NUM: 'Num',
  DEU: 'Deut',
  JOS: 'Josh',
  JDG: 'Judg',
  RUT: 'Ruth',
  '1SA': '1 Sam',
  '2SA': '2 Sam',
  '1KI': '1 Kgs',
  '2KI': '2 Kgs',
  '1CH': '1 Chr',
  '2CH': '2 Chr',
  EZR: 'Ezra',
  NEH: 'Neh',
  EST: 'Esth',
  JOB: 'Job',
  PSA: 'Ps',
  PRO: 'Prov',
  ECC: 'Eccl',
  SNG: 'Song',
  ISA: 'Isa',
  JER: 'Jer',
  LAM: 'Lam',
  EZK: 'Ezek',
  DAN: 'Dan',
  HOS: 'Hos',
  JOL: 'Joel',
  AMO: 'Amos',
  OBA: 'Obad',
  JON: 'Jonah',
  MIC: 'Mic',
  NAM: 'Nah',
  HAB: 'Hab',
  ZEP: 'Zeph',
  HAG: 'Hag',
  ZEC: 'Zech',
  MAL: 'Mal',
  MAT: 'Matt',
  MRK: 'Mark',
  LUK: 'Luke',
  JHN: 'John',
  ACT: 'Acts',
  ROM: 'Rom',
  '1CO': '1 Cor',
  '2CO': '2 Cor',
  GAL: 'Gal',
  EPH: 'Eph',
  PHP: 'Phil',
  COL: 'Col',
  '1TH': '1 Thess',
  '2TH': '2 Thess',
  '1TI': '1 Tim',
  '2TI': '2 Tim',
  TIT: 'Titus',
  PHM: 'Phlm',
  HEB: 'Heb',
  JAS: 'Jas',
  '1PE': '1 Pet',
  '2PE': '2 Pet',
  '1JN': '1 John',
  '2JN': '2 John',
  '3JN': '3 John',
  JUD: 'Jude',
  REV: 'Rev',
};

export function englishBookName(bookId: string, fallback?: string): string {
  const id = bookId.toUpperCase();
  return BOOK_EN_NAME[id] ?? fallback ?? id;
}

/** 将主译本目录结构与本译本卷名合并（id / chapter_count 不变）。 */
export function localizeBooksForVersion(
  books: BibleBook[],
  versionId: string | null | undefined,
  localized?: BibleBook[] | null,
): BibleBook[] {
  if (!isEnglishBibleVersion(versionId)) return books;
  const nameById = new Map(
    (localized ?? []).map((b) => [b.id.toUpperCase(), b.name]),
  );
  return books.map((b) => ({
    ...b,
    name: nameById.get(b.id.toUpperCase()) ?? englishBookName(b.id, b.name),
  }));
}

