/// 经卷 id → 英文卷名/简称（KJV 目录兜底）。
library;

const bookEnName = <String, String>{
  'GEN': 'Genesis',
  'EXO': 'Exodus',
  'LEV': 'Leviticus',
  'NUM': 'Numbers',
  'DEU': 'Deuteronomy',
  'JOS': 'Joshua',
  'JDG': 'Judges',
  'RUT': 'Ruth',
  '1SA': '1 Samuel',
  '2SA': '2 Samuel',
  '1KI': '1 Kings',
  '2KI': '2 Kings',
  '1CH': '1 Chronicles',
  '2CH': '2 Chronicles',
  'EZR': 'Ezra',
  'NEH': 'Nehemiah',
  'EST': 'Esther',
  'JOB': 'Job',
  'PSA': 'Psalms',
  'PRO': 'Proverbs',
  'ECC': 'Ecclesiastes',
  'SNG': 'Song of Solomon',
  'ISA': 'Isaiah',
  'JER': 'Jeremiah',
  'LAM': 'Lamentations',
  'EZK': 'Ezekiel',
  'DAN': 'Daniel',
  'HOS': 'Hosea',
  'JOL': 'Joel',
  'AMO': 'Amos',
  'OBA': 'Obadiah',
  'JON': 'Jonah',
  'MIC': 'Micah',
  'NAM': 'Nahum',
  'HAB': 'Habakkuk',
  'ZEP': 'Zephaniah',
  'HAG': 'Haggai',
  'ZEC': 'Zechariah',
  'MAL': 'Malachi',
  'MAT': 'Matthew',
  'MRK': 'Mark',
  'LUK': 'Luke',
  'JHN': 'John',
  'ACT': 'Acts',
  'ROM': 'Romans',
  '1CO': '1 Corinthians',
  '2CO': '2 Corinthians',
  'GAL': 'Galatians',
  'EPH': 'Ephesians',
  'PHP': 'Philippians',
  'COL': 'Colossians',
  '1TH': '1 Thessalonians',
  '2TH': '2 Thessalonians',
  '1TI': '1 Timothy',
  '2TI': '2 Timothy',
  'TIT': 'Titus',
  'PHM': 'Philemon',
  'HEB': 'Hebrews',
  'JAS': 'James',
  '1PE': '1 Peter',
  '2PE': '2 Peter',
  '1JN': '1 John',
  '2JN': '2 John',
  '3JN': '3 John',
  'JUD': 'Jude',
  'REV': 'Revelation',
};

const bookEnAbbr = <String, String>{
  'GEN': 'Gen',
  'EXO': 'Ex',
  'LEV': 'Lev',
  'NUM': 'Num',
  'DEU': 'Deut',
  'JOS': 'Josh',
  'JDG': 'Judg',
  'RUT': 'Ruth',
  '1SA': '1 Sam',
  '2SA': '2 Sam',
  '1KI': '1 Kgs',
  '2KI': '2 Kgs',
  '1CH': '1 Chr',
  '2CH': '2 Chr',
  'EZR': 'Ezra',
  'NEH': 'Neh',
  'EST': 'Esth',
  'JOB': 'Job',
  'PSA': 'Ps',
  'PRO': 'Prov',
  'ECC': 'Eccl',
  'SNG': 'Song',
  'ISA': 'Isa',
  'JER': 'Jer',
  'LAM': 'Lam',
  'EZK': 'Ezek',
  'DAN': 'Dan',
  'HOS': 'Hos',
  'JOL': 'Joel',
  'AMO': 'Amos',
  'OBA': 'Obad',
  'JON': 'Jonah',
  'MIC': 'Mic',
  'NAM': 'Nah',
  'HAB': 'Hab',
  'ZEP': 'Zeph',
  'HAG': 'Hag',
  'ZEC': 'Zech',
  'MAL': 'Mal',
  'MAT': 'Matt',
  'MRK': 'Mark',
  'LUK': 'Luke',
  'JHN': 'John',
  'ACT': 'Acts',
  'ROM': 'Rom',
  '1CO': '1 Cor',
  '2CO': '2 Cor',
  'GAL': 'Gal',
  'EPH': 'Eph',
  'PHP': 'Phil',
  'COL': 'Col',
  '1TH': '1 Thess',
  '2TH': '2 Thess',
  '1TI': '1 Tim',
  '2TI': '2 Tim',
  'TIT': 'Titus',
  'PHM': 'Phlm',
  'HEB': 'Heb',
  'JAS': 'Jas',
  '1PE': '1 Pet',
  '2PE': '2 Pet',
  '1JN': '1 John',
  '2JN': '2 John',
  '3JN': '3 John',
  'JUD': 'Jude',
  'REV': 'Rev',
};

bool isEnglishBibleVersion(String? versionId) {
  final id = (versionId ?? '').trim().toLowerCase();
  return id == 'kjv' || id == 'niv';
}

String englishBookName(String bookId, {String? fallback}) {
  final id = bookId.toUpperCase();
  return bookEnName[id] ?? fallback ?? id;
}

String bibleBookAbbrFor(String bookId, String name, {bool english = false}) {
  if (english) {
    return bookEnAbbr[bookId.toUpperCase()] ??
        (name.split(' ').take(2).join(' '));
  }
  return bibleBookAbbrZh(name);
}

String bibleBookAbbrZh(String name) {
  const zh = {
    '创世记': '创',
    '出埃及记': '出',
    '利未记': '利',
    '民数记': '民',
    '申命记': '申',
    '约书亚记': '书',
    '士师记': '士',
    '路得记': '得',
    '撒母耳记上': '撒上',
    '撒母耳记下': '撒下',
    '列王纪上': '王上',
    '列王纪下': '王下',
    '历代志上': '代上',
    '历代志下': '代下',
    '以斯拉记': '拉',
    '尼希米记': '尼',
    '以斯帖记': '斯',
    '约伯记': '伯',
    '诗篇': '诗',
    '箴言': '箴',
    '传道书': '传',
    '雅歌': '歌',
    '以赛亚书': '赛',
    '耶利米书': '耶',
    '耶利米哀歌': '哀',
    '以西结书': '结',
    '但以理书': '但',
    '何西阿书': '何',
    '约珥书': '珥',
    '阿摩司书': '摩',
    '俄巴底亚书': '俄',
    '约拿书': '拿',
    '弥迦书': '弥',
    '那鸿书': '鸿',
    '哈巴谷书': '哈',
    '西番雅书': '番',
    '哈该书': '该',
    '撒迦利亚书': '亚',
    '玛拉基书': '玛',
    '马太福音': '太',
    '马可福音': '可',
    '路加福音': '路',
    '约翰福音': '约',
    '使徒行传': '徒',
    '罗马书': '罗',
    '哥林多前书': '林前',
    '哥林多后书': '林后',
    '加拉太书': '加',
    '以弗所书': '弗',
    '腓立比书': '腓',
    '歌罗西书': '西',
    '帖撒罗尼迦前书': '帖前',
    '帖撒罗尼迦后书': '帖后',
    '提摩太前书': '提前',
    '提摩太后书': '提后',
    '提多书': '多',
    '腓利门书': '门',
    '希伯来书': '来',
    '雅各书': '雅',
    '彼得前书': '彼前',
    '彼得后书': '彼后',
    '约翰一书': '约一',
    '约翰二书': '约二',
    '约翰三书': '约三',
    '犹大书': '犹',
    '启示录': '启',
  };
  return zh[name] ?? (name.isEmpty ? '' : name.substring(0, 1));
}
